### ISSUE TITLE
Multiple text domain issue

### ISSUE THREAD

**Issue by ernilambar** [ernilambar/ns-theme-check#15]
Theme Name: `Phpkida`
Text Domain: `Phpkida`

Sniffer message:
`Mismatch text domain. Expected 'Phpkida' or 'hybrid-core' but got 'phpkida'.`

May be we should rework on this.
```
$text_domains = array(
    // Current theme text domain.
    $theme->get( 'TextDomain' ),
    // Frameworks.
    'hybrid-core',
);
```

Also, in this `If we have a long list of framework text domains people will get confused. We will need a way to detect if a framework is being used and only then include that text domain to the whitelist.` since both issues are related.

**Comment by grappler** [comment]
The problem in this example is that the text domain is incorrect.

It might be better to use the theme slug in the meantime instead of the text domain.

We need a separate sniff that check the style.css header data so that we can give out an error when the text domain is missing or defined incorrectly.

**Comment by ernilambar** [comment]
Also it would be good if we can find a way to display this message only once in a theme. I tried one theme in review and I got 150+ ERRORS of same message. :smile:

**Comment by grappler** [comment]
I am not sure. In the future only the theme author will see them when uploading the theme. Potentially you could create a summary view using the JSON. For example: This theme has x, y and z issues. Run the theme check to get the full results.
