### ISSUE TITLE
Idea for update - choose standard

### ISSUE THREAD

**Issue by dingo-d** [ernilambar/ns-theme-check#2]
It would be cool to add the option with which standard to sniff the theme - Core, Theme, VIP etc. Kinda like:

![suggestion_sniffs](https://cloud.githubusercontent.com/assets/8638515/22141648/4b4ed12a-def3-11e6-95d3-2bf0bbbf9096.jpg)

**Comment by ernilambar** [comment]
It is great option to have. But in the context of TRT, it is suitable to add that dropdown because we will always be using `WordPress Theme` standard.

**Comment by dingo-d** [comment]
Yes, for TRT it's not necessary, but in general it could be a great addition :)

**Comment by grappler** [comment]
I think it would be a good idea. We would just need to be clear that WordPress-Theme is the main one.

Instead of having to run the sniff multiple times, I think a checkbox might be better than a dropdown. This way you can choose which rulesets you want to run.

As "NS Theme Check" will not be the official plugin it would be nice to test a few ideas and see what feedback people give.

This would be for a separate issue but we are seeing people struggle with the difference between Errors and Warnings.

**Comment by ernilambar** [comment]
> Instead of having to run the sniff multiple times, I think a checkbox might be better than a dropdown. This way you can choose which rulesets you want to run.

@grappler Is it possible to set multiple `standard`? Can you please point me how we can implement this? :)

**Comment by grappler** [comment]
> Is it possible to set multiple standard?

Yes

> Can you please point me how we can implement this?

Sure `phpcs --standard=WordPress-Theme,WordPress-Core` or `$values['standard']    = 'WordPress-Theme,WordPress-Core';`

**Comment by ernilambar** [comment]
Fixed in https://github.com/ernilambar/ns-theme-check/pull/11
